config/routes.rb
BusinessSkillsDay::Application.routes.draw do

  # Define the root route, which will go the index action of the Main controller.
  root :to => 'main#index'

  # Session controller.
  get '/login' => 'sessions#new', :as => :new_login
  post '/login' => 'sessions#create', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout, :via => :all

  # Registration resource to allow a user to apply for a new chapter.
  resources :registrations, :only => [:index, :new, :create]

  # Account resource to access the current user's account.
  resource :account, :only => [:show, :edit, :update]

  # Chapter (and nested) resource.
  resources :chapters, :only => [:show, :edit, :update] do
    resources :advisers do get :delete, :on => :member end
    resources :students do get :delete, :on => :member end
    resources :teams do get :delete, :on => :member end
    get :results, :on => :member
  end

  # Admin namespace.
  namespace :admin do
    resources :chapters,  :except => [:show, :edit, :update] do get :delete, :on => :member end
    resources :advisers,  :except => [:new, :create, :show, :edit, :update]
    resources :students,  :except => [:new, :create, :show, :edit, :update]
    resources :teams,     :except => [:new, :create, :show, :edit, :update]

    resources :events do
      get :delete, :on => :member

      resources :results, :except => [:show] do
        get :delete, :on => :member
      end
    end

    resources :accounts do get :delete, :on => :member end

    resources :registrations, :only => [:index, :show, :edit, :update, :destroy] do
      get :delete, :on => :member
      get :confirm, :on => :member
      post :approve, :on => :member
    end

    # Tools like nametags, powerpoints, etc.
    scope :tools do
      get '/' => 'tools#index', :as => 'tools'
      get 'nametags' => 'tools#nametags'
    end

    get '/results' => 'results#main', :as => 'results'
    get '/' => 'main#index'
  end

end

app/models/events/event.rb
class Event < ActiveRecord::Base
  # number:integer
  # name:string
  # nine_ten:boolean
  # type:string (internal, for STI)

  default_scope ->{ order(:number) }

  def self.types
    types = []
    types << 'WrittenEvent'
    types << 'IndividualPerformanceEvent'
    types << 'TeamPerformanceEvent'
  end

  def self.attributes_protected_by_default
    %w(id)
  end

  has_many :results, :class_name => 'Result', :inverse_of => :event

  # Validation
  validates :number, :presence => true, :numericality => true, :uniqueness => true
  validates :name, :presence => true, :uniqueness => true
  validates :type, :presence => true, :inclusion => { :in => Event.types }

  def students_for_chapter(chapter)
    if respond_to? :students and chapter.present?
      students.joins(:chapter).where(['chapters.id = ?', chapter])
    else
      []
    end
  end

  def participants
    []
  end

  def to_s
    s = name
    s += ' (9 - 10)' if nine_ten?
    s
  end

  def to_param
    "#{id} #{to_s}".parameterize
  end

end

app/models/events/individual_performance_event.rb
class IndividualPerformanceEvent < PerformanceEvent

  has_and_belongs_to_many :students,
                          :join_table => 'events_students',
                          :foreign_key => 'event_id'

  def participants
    students
  end

end

app/models/events/performance_event.rb
class PerformanceEvent < Event

end

app/models/events/results/result.rb
class Result < ActiveRecord::Base
  # score:integer
  # event_id:integer
  # participant_id:integer
  # type:string (internal, for STI)

  default_scope ->{ order('score DESC') }
  scope :top_five, ->{ limit(5) }

  def self.types
    types = []
    types << StudentResult
    types << TeamResult
    types.map { |type| type.name }
  end

  def self.attributes_protected_by_default
    %w(id)
  end

  belongs_to :event, :inverse_of => :results
  belongs_to :participant, :class_name => 'Student'

  # Validations
  validates :score, :presence => true, :numericality => true
  validates :event, :presence => true
  validates :participant, :presence => true
  validate :unique_participant_on_event

  def rank
    rank = event.results.index(self) + 1
    rank unless rank > 5
  end

  def to_param
    if new_record?
      ""
    else
      "#{id} #{rank.ordinalize if rank.present?} #{participant.to_s}".parameterize
    end
  end

  private

    def unique_participant_on_event
      if event.present? && participant.present?
        errors.add(:participant, 'was already awarded a different rank') unless event.results.where{ |q| (q.participant_id == participant.id) & (q.id != id)}.count == 0
      end
    end
end

app/models/events/results/student_result.rb
class StudentResult < Result
  belongs_to :participant, :class_name => 'Student'
end

app/models/events/results/team_result.rb
class TeamResult < Result
  belongs_to :participant, :class_name => 'Team'
end

app/models/events/team_performance_event.rb
class TeamPerformanceEvent < PerformanceEvent

  has_many :teams, :foreign_key => 'event_id'

  before_destroy :handle_destroy

  def participants
    teams
  end

  def handle_destroy
    teams.each { |t| t.destroy }
  end

end

app/models/events/written_event.rb
class WrittenEvent < Event

  has_and_belongs_to_many :students,
                          :join_table => 'events_students',
                          :foreign_key => 'event_id'

  def participants
    students
  end

end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < AdminController

    before_filter :get_event

    def index
      @admin_events = Event.all.page(params[:page])
    end

    def show
    end

    def new
      @admin_event = Event.new
    end

    def edit
    end

    def create
      event_params = admin_event_params

      # Make sure the type parameter is valid.
      raise 'Event type is not valid' unless Event.types.include?(event_params[:type])
      @admin_event = (event_params[:type].constantize).new(event_params)

      if @admin_event.save
        redirect_to admin_event_path(@admin_event), notice: 'Event was successfully created.'
      else
        render action: "new"
      end
    end

    def update
      if @admin_event.update_attributes(admin_event_params)
        redirect_to admin_event_path(@admin_event), notice: 'Event was successfully updated.'
      else
        render action: "edit"
      end
    end

    def destroy
      @admin_event.destroy
      redirect_to admin_events_url, notice: "Successfully deleted #{@admin_event.type.underscore.humanize.downcase} #{@admin_event.name}"
    end

    private

      def get_event
        @admin_event = Event.find(params[:id]) if params[:id]
      end

      def admin_event_params
        params.require(:admin_event).permit(:number, :name, :nine_ten, :type)
      end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def event_with_icon(event)
    return '' unless event.present?

    icon = case event
             when WrittenEvent
               'icon-pencil'
             when IndividualPerformanceEvent
               'icon-user'
             when TeamPerformanceEvent
               'icon-group'
           end
    "<i class=\"#{icon}\"></i> #{event.to_s}".html_safe
  end

  def events_with_icons(events, separator = '<br>')
    events.map { |ev| event_with_icon ev }.to_sentence(
        :words_connector => separator,
        :two_words_connector => separator,
        :last_word_connector => separator
    ).html_safe
  end

  def event_type(event)
    case event
      when WrittenEvent
        'Written'
      when IndividualPerformanceEvent
        'Individual Performance'
      when TeamPerformanceEvent
        'Team Performance'
      else
        'Event'
    end
  end

  def participants_type(event)
    case event
      when WrittenEvent
        'Students'
      when TeamPerformanceEvent
        'Teams'
      else
        'Participants'
    end
  end

  def participants_count(event)
    if event.is_a? TeamPerformanceEvent
      pluralize event.participants.count, 'team'
    else
      pluralize event.participants.count, 'student'
    end
  end
end

app/views/admin/events/_form.html.haml
= simple_form_for(@admin_event, :as => :admin_event, :url => admin_event_path(@admin_event), :html => { :class => 'form form-horizontal' }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :number, :hint => 'Event number must be unique.'
    = f.input :name, :hint => 'Event name must be unique.'
    = f.input :type, :as => :select, :collection => Event.types, :label_method => ->(t){ t.underscore.humanize }
    = f.input :nine_ten, :label => 'Only grades 9 and 10?', :wrapper => :inline_checkbox

  .form-actions
    = f.button :submit

app/views/admin/events/_index.html.haml
- if !defined?(show_all)
  - show_all = true
- show_max = 5

.row-fluid
  .span12.section
    - if defined? section_header
      = section_header
    - else
      %h4.title= icon_title_event 'Events:'

    - if can? :create, :event
      .row-fluid
        .span12.section
          %h4.title= icon_title 'cog', 'Actions:'
          %div
            = link_to_new Event, new_admin_event_path

    %div
      - if events.count > 0
        %p.muted= icon_title_info "There are #{pluralize events.count, 'registered event'}."

        %table.table
          %th Number
          %th Name
          %th Type
          %th Participants
          %th

          - if !show_all
            - events.limit(show_max).each do |e|
              = render :partial => 'admin/events/table_row', :locals => { :event => e }
          - else
            - events.each do |e|
              = render :partial => 'admin/events/table_row', :locals => { :event => e }

        - if show_all
          = will_paginate events
        - if !show_all && events.count > show_max
          = link_to 'View all events', admin_events_path, :class => 'btn btn-mini'

      - else
        %div.alert.alert-error= icon_title_exclamation 'There are no registered chapters.'

app/views/admin/events/_results_table_row.html.haml
%tr
  %td.event-number= event.number
  %td.event-name= link_to event_with_icon(event), admin_event_path(event)
  %td.event-type= event_type(event)
  %td.event-results= pluralize(event.results.count, 'result')
  %td
    = link_to icon_title_result('View Results'), admin_event_results_path(event), :class => 'btn btn-mini'

app/views/admin/events/_table_row.html.haml
%tr
  %td.event-number= event.number
  %td.event-name= link_to event_with_icon(event), admin_event_path(event)
  %td.event-type= event_type(event)
  %td.event-participants= participants_count(event)
  %td
    = link_to_edit event, edit_admin_event_path(event)
    = link_to_delete event, delete_admin_event_path(event)

app/views/admin/events/delete.html.haml
- title "Deleting #{@admin_event.type.underscore.humanize.downcase} #{@admin_event.name}"

- content_for :sidebar do
  = render :partial => 'admin/sidebar'

- if notice.present?
  %p#notice.alert.alert-success= notice

%h1
  %i.icon-remove
  Deleting #{@admin_event.type.underscore.humanize.downcase} #{@admin_event.name}

.row-fluid
  .section.span12
    %h4.title= icon_title_question 'Confirmation:'

    %div
      %p Are you sure you want to delete #{@admin_event.type.underscore.humanize.downcase} <strong>#{@admin_event.name}</strong>?
      %p Doing so will trigger the following actions:
      %ul
        - case @admin_event.type
        - when 'TeamPerformanceEvent'
          - @admin_event.participants.each do |t|
            %li Delete team for chapter #{link_to t.chapter.name, chapter_path(t.chapter)}
        - else
          %li Remove this event from #{pluralize(@admin_event.participants.count, 'student')}

    %div
      = link_to icon_title_delete,  admin_event_path(@admin_event), :method => :delete, :class => 'btn btn-small btn-danger'
      = link_to icon_title('arrow-left', 'Cancel'), :back, :class => 'btn btn-small'

app/views/admin/events/edit.html.haml
- title "Editing #{@admin_event}"

- content_for :sidebar do
  = render :partial => 'admin/sidebar'

.row-fluid
  .span12
    %h1= icon_title_edit "Editing #{@admin_event}"

.row-fluid
  .span12
    = render :partial => 'form'

app/views/admin/events/index.html.haml
- title 'Events'

- content_for :sidebar do
  = render :partial => 'admin/sidebar'

- if notice.present?
  %p#notice.alert.alert-success= notice

- content_for :section_header do
  %h1= icon_title_event 'Events'

= render :partial => 'index', :locals => { :events => @admin_events, :section_header => content_for(:section_header), :show_all => true }

app/views/admin/events/new.html.haml
- title 'New event'

- content_for :sidebar do
  = render :partial => 'admin/sidebar'

.row-fluid
  .span12
    %h1= icon_title_new 'Adding a new event'

.row-fluid
  .span12
    = render :partial => 'form'

app/views/admin/events/show.html.haml
- title @admin_event

- content_for :sidebar do
  = render :partial => 'admin/sidebar'

- if notice.present?
  %p#notice.alert.alert-success= notice

.row-fluid
  .span12.section
    %h1= event_with_icon @admin_event
    %div
      - if can?(:edit, @admin_event) || can?(:delete, @admin_event)
        .row-fluid
          .span12.section
            %h4.title= icon_title 'cog', 'Actions:'
            %div
              = link_to_edit @admin_event, edit_admin_event_path(@admin_event)
              = link_to_delete @admin_event, delete_admin_event_path(@admin_event)

      = render :partial => 'admin/results/index', :locals => { :event => @admin_event, :results => @admin_event.results, :preview => true }

      - if @admin_event.is_a? TeamPerformanceEvent
        .row-fluid
          .span12.section
            %h4.title= icon_title_team 'Teams:'

            %div
              %table.table
                %th ID
                %th Event
                %th Chapter
                %th Students
                %th

                - @admin_event.participants.ordered.each do |t|
                  = render :partial => 'admin/teams/table_row', :locals => { :team => t }


      - else
        .row-fluid
          .span12.section
            %h4.title= icon_title_student 'Students:'

            %div
              %table.table
                %th ID
                %th Name
                %th Chapter
                %th

                - @admin_event.participants.ordered.each do |s|
                  = render :partial => 'admin/students/table_row', :locals => { :student => s }