config/routes.rb
BusinessSkillsDay::Application.routes.draw do

  # Define the root route, which will go the index action of the Main controller.
  root :to => 'main#index'

  # Session controller.
  get '/login' => 'sessions#new', :as => :new_login
  post '/login' => 'sessions#create', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout, :via => :all

  # Registration resource to allow a user to apply for a new chapter.
  resources :registrations, :only => [:index, :new, :create]

  # Account resource to access the current user's account.
  resource :account, :only => [:show, :edit, :update]

  # Chapter (and nested) resource.
  resources :chapters, :only => [:show, :edit, :update] do
    resources :advisers do get :delete, :on => :member end
    resources :students do get :delete, :on => :member end
    resources :teams do get :delete, :on => :member end
    get :results, :on => :member
  end

  # Admin namespace.
  namespace :admin do
    resources :chapters,  :except => [:show, :edit, :update] do get :delete, :on => :member end
    resources :advisers,  :except => [:new, :create, :show, :edit, :update]
    resources :students,  :except => [:new, :create, :show, :edit, :update]
    resources :teams,     :except => [:new, :create, :show, :edit, :update]

    resources :events do
      get :delete, :on => :member

      resources :results, :except => [:show] do
        get :delete, :on => :member
      end
    end

    resources :accounts do get :delete, :on => :member end

    resources :registrations, :only => [:index, :show, :edit, :update, :destroy] do
      get :delete, :on => :member
      get :confirm, :on => :member
      post :approve, :on => :member
    end

    # Tools like nametags, powerpoints, etc.
    scope :tools do
      get '/' => 'tools#index', :as => 'tools'
      get 'nametags' => 'tools#nametags'
    end

    get '/results' => 'results#main', :as => 'results'
    get '/' => 'main#index'
  end

end

app/models/student.rb
class Student < ActiveRecord::Base
  # name:string
  # grade:integer

  default_scope ->{ order(:name) }
  scope :ordered, ->{ joins(:chapter).reorder('chapters.name', 'students.name') }

  before_save :handle_team
  before_destroy :handle_destroy

  belongs_to :chapter, :inverse_of => :students
  belongs_to :team, :inverse_of => :students
  has_and_belongs_to_many :events, :extend => StudentEventsAssociationExtension
  has_many :results, :class_name => 'StudentResult', :foreign_key => 'participant_id'

  # Validations
  validates :name, :presence => true
  validates :grade, :presence => true, :inclusion => 9..12
  validates :chapter, :presence => true

  validate :validate_grade
  validate :validate_events

  def validate_grade
    events.each do |ev|
      if ev.nine_ten? && (11..12).include?(grade)
        errors.add(:grade, 'does not match with registered grade 9/10 events')
        return false
      end
    end
  end

  def validate_events
    errors.add(:events, "Can't participate in more than 3 events (including team events)") unless events.count <= 3
    errors.add(:events, "Can't participate in more than 1 performance event") unless events.select{ |e| e.is_a? PerformanceEvent }.count <= 1
  end

  def handle_team
    return true unless self.team_id_changed?

    if team.blank?
      # Remove any team events from the student.
      self.events.delete(self.events.where(:type => 'TeamPerformanceEvent'))
    else
      if !self.events.include?(team.event) && !(self.events << team.event)
        self.team_id = nil
        return false
      end
    end
  end

  def handle_destroy
    # Remove this student from all of its events.
    events.each { |ev| ev.respond_to?(:students) && ev.students.delete(self) }

    # Remove this student from its team.
    team.students.delete self if team.present?
  end

  def can_register_for_event?(event)
    return true if events.include?(event)

    return false unless events.count < 3
    return false if event.present? && event.nine_ten && (11..12).include?(grade)
    return false if event.present? && event.is_a?(WrittenEvent) && !(events.where{type == 'WrittenEvent' }.count < 3)
    return false if event.present? && event.is_a?(PerformanceEvent) && events.where{type == 'PerformanceEvent' }.exists?

    true
  end

  def can_register_for_team?(team)
    return true if self.team == team

    return false unless events.count < 3
    return false unless events.select { |ev| ev.is_a? PerformanceEvent }.count == 0

    true
  end

  def to_s
    name
  end

  def to_param
    "#{id} #{name}".parameterize
  end

  def to_unique_number
    "#{chapter.id.to_s.rjust(3, '0')}-#{id.to_s.rjust(4, '0')}"
  end

end

app/controllers/admin/students_controller.rb
module Admin
  class StudentsController < AdminController
    # GET /admin/students
    def index
      @admin_students = Student.ordered.page(params[:page])
    end

    # GET /admin/students/new
    def new
      @admin_student = Student.new
    end

    # DELETE /admin/students/1
    def destroy
      @admin_student = Student.find(params[:id])
      @admin_student.destroy

      redirect_to admin_students_url
    end

    private

    def admin_student_params
      params.require(:admin_student).permit()
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ChapterAuthenticationController

  before_filter :get_student
  authorize_resource

  def index
    @students = @chapter.students.page(params[:page])
  end

  def show
  end

  def new
    @student = @chapter.students.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student }
    end
  end

  def edit
  end

  def create
    begin
      @student = @chapter.students.build()
      success = @student.update_attributes(student_params)
    rescue
      success = false
    end

    respond_to do |format|
      if success && @student.save
        format.html { redirect_to chapter_student_url(@chapter, @student), notice: 'Student was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    begin
      success = @student.update_attributes(student_params)
    rescue
      success = false
    end

    respond_to do |format|
      if success
        format.html { redirect_to chapter_student_url(@chapter, @student), notice: 'Student was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def delete
  end

  def destroy
    @student.destroy
    redirect_to chapter_students_url(@chapter), notice: "Successfully deleted student #{@student.name}"
  end

  private

    def get_student
      @student = @chapter.students.find(params[:id]) if params[:id]
    end

    def student_params
      p = params.require(:student).permit(:name, :grade, :team_id, :event_ids => [])

      if p[:team_id].present? && Team.find(p[:team_id])
        p[:event_ids] << Team.find(p[:team_id]).event.id
      end

      p
    end
end

app/views/students/_form.html.haml
= simple_form_for([@chapter, @student], :html => { :class => 'form-horizontal' }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :grade, :collection => 9..12
    = f.association :events,
                    :as => :events,
                    :label_method => :to_s,
                    :collection => Event.where(['type != ?', 'TeamPerformanceEvent'])

    = f.association :team, :collection => @chapter.teams.select { |t| t.can_register_student?(@student) }

  .form-actions
    = f.button :submit

app/views/students/_index.html.haml
- unless defined?(show_max)
  - show_all = true
- else
  - show_all = false

.row-fluid
  .section.span12
    - if defined? section_header
      = section_header
    - else
      %h4.title= icon_title_student 'Students:'

    %div
      - if students.count > 0
        %p.muted
          %i.icon-info
          You have #{pluralize students.count, 'registered student'}.
          - if can? :create, Student
            = link_to 'Add another?', new_chapter_student_path(@chapter)

        %table.table
          %th ID
          %th Name
          %th Grade
          %th Events
          %th

          - if show_all
            - students.each do |s|
              = render :partial => 'students/table_row', :locals => { :student => s }
          - else
            - students.limit(show_max).each do |s|
              = render :partial => 'students/table_row', :locals => { :student => s }

        - if show_all
          = will_paginate students
        - elsif show_max < students.count
          = link_to 'View all students', chapter_students_path(@chapter), :class => 'btn btn-small'

      - else
        %div.alert.alert-error
          %i.icon-exclamation
          You have no registered students.
          - if can? :create, Student
            = link_to 'Add one.', new_chapter_student_path(@chapter)

app/views/students/_table_row.html.haml
%tr
  %td.student-id= student.id
  %td.student-name= link_to student.name, chapter_student_path(student.chapter, student)
  %td.student-grade= student.grade
  %td.student-events= events_with_icons(student.events)
  %td
    = link_to_edit student, edit_chapter_student_path(student.chapter, student)
    = link_to_delete student, delete_chapter_student_path(student.chapter, student)

app/views/students/delete.html.haml
- title "Deleting student #{@student.name}"

- content_for :sidebar do
  = render :partial => 'chapters/sidebar', :locals => { :chapter => @chapter, :student => @student }

- if notice.present?
  %p#notice.alert.alert-success= notice

%h1
  %i.icon-remove
  Deleting student #{@student.name}
  %small= link_to "[#{@chapter.name}]", chapter_path(@chapter)

.row-fluid
  .section.span12
    %h4.title= icon_title_question 'Confirmation:'

    %div
      %p Are you sure you want to delete student <strong>#{@student.name}</strong>?
      %p Doing so will trigger the following actions:
      %ul
        - @student.events.each do |e|
          %li Student will be removed from event #{event_with_icon(e)}
        - if @student.team.present?
          %li Student will be removed from team #{@student.team}

    %div
      = link_to icon_title_delete,  chapter_student_path(@chapter, @student), :method => :delete, :class => 'btn btn-small btn-danger'
      = link_to icon_title('arrow-left', 'Cancel'), :back, :class => 'btn btn-small'

app/views/students/edit.html.haml
- title "Editing student #{@student.name}"

- content_for :sidebar do
  = render :partial => 'chapters/sidebar', :locals => { :chapter => @chapter, :student => @student }

.row-fluid
  .span12
    %h1= icon_title_edit "Editing information for #{@student.name}"

.row-fluid.form-split
  .span7.form-main
    = render 'form'

  .span5.form-side-information.section
    :markdown
      <h4 class="title"><i class="icon-exclamation-sign"></i> Registration Information</h4>

      There are certain limitations on what events a student may register for:</span>

      *   Students may register for at most 3 events
      <span style="display:none;">*   Students may register for at most 3 written events</span>
      *   Students may register for at most 1 performance (individual or team) event
      *   Only students in grades 9 or 10 may register for an event marked as 9 - 10

      There are further limitations based on the size of your chapter:

      *   Chapters with **between 0 and 24 students** may register at most **2 students** for a particular individual performance event
      *   Chapters with **between 25 and 49 students** may register at most **3 students** for a particular individual performance event
      *   Chapters with **50 or more students** may register at most **4** students for a particular individual performance event

      You currently have **#{pluralize(@chapter.students.count, 'student')}** in your chapter.

app/views/students/index.html.haml
- title "Students for #{@chapter.name}"

- content_for :sidebar do
  = render :partial => 'chapters/sidebar', :locals => { :chapter => @chapter }

- if notice.present?
  %p#notice.alert.alert-success= notice

- content_for :section_header do
  %h1
    %i.icon-user
    Students for
    = link_to "#{@chapter.name}", chapter_path(@chapter)

= render :partial => 'index', :locals => { :students => @students, :section_header => content_for(:section_header) }

app/views/students/new.html.haml
- title "New student for #{@chapter.name}"

- content_for :sidebar do
  = render :partial => 'chapters/sidebar', :locals => { :chapter => @chapter, :student => @student }

.row-fluid
  .span12
    %h1= icon_title_new 'Adding a new student'

.row-fluid
  .span12
    = render 'form'

app/views/students/show.html.haml
- title "Student #{@student.name}"

- content_for :sidebar do
  = render :partial => 'chapters/sidebar', :locals => { :chapter => @chapter, :student => @student }

- if notice.present?
  %p#notice.alert.alert-success= notice

%h1
  %i.icon-user
  = @student.name
  %small= link_to "[#{@chapter.name}]", chapter_path(@chapter)

.row-fluid
  .section.span12
    %h4.title= icon_title_info 'Information:'

    %div
      %table.info-table
        %tr
          %td
            %strong ID:
          %td= @student.id
        %tr
          %td
            %strong Grade:
          %td= @student.grade

.row-fluid
  .section.span12
    %h4.title= icon_title_event 'Events:'

    - if @student.events.any?
      %div
        %table.table
          %tr
            %th Name

          - @student.events.each do |ev|
            %tr
              %td.event-name= event_with_icon(ev)
    - else
      %div.alert.alert-error
        %i.icon-exclamation
        #{@student.name} is not registered for any events.
        = link_to 'Add some.', edit_chapter_student_path(@chapter, @student)

- if @student.team.present?
  .row-fluid
    .section.span12
      %h4.title= icon_title_team 'Team:'

      %div
        %table.info-table
          %tr
            %td
              %strong Event:
            %td
              = link_to chapter_team_path(@chapter, @student.team) do
                = event_with_icon(@student.team.event)

          %tr
            %td
              %strong Members:
            %td
              %table.table
                %tr
                  %th ID
                  %th Name
                  %th Grade

                - @student.team.students.each do |student|
                  %tr
                    %td.student-id= student.id
                    %td.student-name= link_to student.name, chapter_student_path(student.chapter, student)
                    %td.student-grade= student.grade

- if @student.results.count > 0 || (@student.team.present? && @student.team.result.present?)
  .row-fluid
    .section.span12
      %h4.title= icon_title_result 'Results:'

      %div
        %table.table.results
          - @student.results.each do |r|
            = render :partial => 'results/table_row', :locals => { :result => r }

          - if @student.team.present? && @student.team.result.present?
            = render :partial => 'results/table_row', :locals => { :result => @student.team.result }