config/routes.rb
BusinessSkillsDay::Application.routes.draw do

  # Define the root route, which will go the index action of the Main controller.
  root :to => 'main#index'

  # Session controller.
  get '/login' => 'sessions#new', :as => :new_login
  post '/login' => 'sessions#create', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout, :via => :all

  # Registration resource to allow a user to apply for a new chapter.
  resources :registrations, :only => [:index, :new, :create]

  # Account resource to access the current user's account.
  resource :account, :only => [:show, :edit, :update]

  # Chapter (and nested) resource.
  resources :chapters, :only => [:show, :edit, :update] do
    resources :advisers do get :delete, :on => :member end
    resources :students do get :delete, :on => :member end
    resources :teams do get :delete, :on => :member end
    get :results, :on => :member
  end

  # Admin namespace.
  namespace :admin do
    resources :chapters,  :except => [:show, :edit, :update] do get :delete, :on => :member end
    resources :advisers,  :except => [:new, :create, :show, :edit, :update]
    resources :students,  :except => [:new, :create, :show, :edit, :update]
    resources :teams,     :except => [:new, :create, :show, :edit, :update]

    resources :events do
      get :delete, :on => :member

      resources :results, :except => [:show] do
        get :delete, :on => :member
      end
    end

    resources :accounts do get :delete, :on => :member end

    resources :registrations, :only => [:index, :show, :edit, :update, :destroy] do
      get :delete, :on => :member
      get :confirm, :on => :member
      post :approve, :on => :member
    end

    # Tools like nametags, powerpoints, etc.
    scope :tools do
      get '/' => 'tools#index', :as => 'tools'
      get 'nametags' => 'tools#nametags'
    end

    get '/results' => 'results#main', :as => 'results'
    get '/' => 'main#index'
  end

end

app/models/events/results/result.rb
class Result < ActiveRecord::Base
  # score:integer
  # event_id:integer
  # participant_id:integer
  # type:string (internal, for STI)

  default_scope ->{ order('score DESC') }
  scope :top_five, ->{ limit(5) }

  def self.types
    types = []
    types << StudentResult
    types << TeamResult
    types.map { |type| type.name }
  end

  def self.attributes_protected_by_default
    %w(id)
  end

  belongs_to :event, :inverse_of => :results
  belongs_to :participant, :class_name => 'Student'

  # Validations
  validates :score, :presence => true, :numericality => true
  validates :event, :presence => true
  validates :participant, :presence => true
  validate :unique_participant_on_event

  def rank
    rank = event.results.index(self) + 1
    rank unless rank > 5
  end

  def to_param
    if new_record?
      ""
    else
      "#{id} #{rank.ordinalize if rank.present?} #{participant.to_s}".parameterize
    end
  end

  private

    def unique_participant_on_event
      if event.present? && participant.present?
        errors.add(:participant, 'was already awarded a different rank') unless event.results.where{ |q| (q.participant_id == participant.id) & (q.id != id)}.count == 0
      end
    end
end

app/models/events/results/student_result.rb
class StudentResult < Result
  belongs_to :participant, :class_name => 'Student'
end

app/models/events/results/team_result.rb
class TeamResult < Result
  belongs_to :participant, :class_name => 'Team'
end

app/controllers/admin/results_controller.rb
module Admin
  class ResultsController < AdminController

    before_filter :get_event, :get_result

    def main
      @events = Event.all
      @results = Result.all
    end

    def index
      @results = @event.results.all
    end

    def new
      @result = @event.results.build
    end

    def create
      params = result_params

      # Make sure the type parameter is valid.
      raise 'Result type is not valid' unless Result.types.include?(params[:type])
      @result = @event.results.build(params)


      if @result.save
        redirect_to admin_event_results_url(@event), notice: 'Result was successfully saved.'
      else
        render action: "new"
      end
    end

    def update
      if @result.update_attributes(result_params)
        redirect_to admin_event_results_url(@event), notice: 'Result was successfully updated.'
      else
        render action: "edit"
      end
    end

    def destroy
      @result.destroy
      redirect_to admin_event_results_url(@event), :notice => 'Successfully deleted result.'
    end

    private

      def get_event
        @event ||= Event.find(params[:event_id]) if params[:event_id]
      end

      def get_result
        @result ||= @event.results.find(params[:id]) if params[:id]
      end

      def result_params
        p = params.require(:result).permit(:score, :participant_id)
        p[:type] = @event.type == 'TeamPerformanceEvent' ? 'TeamResult' : 'StudentResult'
        p
      end
  end
end

app/views/admin/results/_form.html.haml
= simple_form_for(@result, :as => :result, :url => admin_event_result_path(@event, @result), :html => { :class => 'form form-horizontal' }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :score, :as => :integer, :hint => 'Score must be an integer'

    - if @event.is_a? TeamPerformanceEvent
      = f.association :participant,
                      :as => :select,
                      :collection => @event.participants,
                      :label_method => ->(team){ team.chapter.name },
                      :label => 'Team',
                      :hint => 'Team must not already have a result'
    - else
      = f.association :participant,
                      :as => :select,
                      :collection => @event.participants,
                      :label => 'Student',
                      :hint => 'Student must not already have a result for this event'

  .form-actions
    = f.button :submit, 'Save Result'
    = link_to icon_title('arrow-left', 'Cancel'), :back, :class => 'btn'

app/views/admin/results/_index.html.haml
- if defined?(preview) && preview
  - shown_results = results.top_five
  - full_view = false
  - columns = [:rank, :chapter, :participant, :score]
- else
  - shown_results = results
  - full_view = true
  - columns = [:rank, :chapter, :participant, :score, :actions]

.row-fluid
  .span12.section
    - if defined? section_header
      = section_header
    - else
      %h4.title= icon_title_result 'Results:'

    - if full_view
      .row-fluid
        .section.span12
          %h4= icon_title 'cog', 'Actions:'
          %div
            = link_to_new Result, new_admin_event_result_path(event)

    %div
      - if shown_results.count > 0
        %table.table
          %tr
            %th Rank
            %th Chapter
            %th= event.type == 'TeamPerformanceEvent' ? 'Team' : 'Student'
            %th Score
            %th

          - shown_results.each do |result|
            = render :partial => 'results/table_row', :locals => { :result => result, :columns => columns }

        - if results.count > shown_results.count
          = link_to icon_title_result('View All Results'), admin_event_results_path(event), :class => 'btn btn-mini'

      - else
        %div.alert.alert-error
          %i.icon-exclamation
          This event has no results.

      - unless full_view
        = link_to 'Manage results', admin_event_results_path(event), :class => 'btn btn-small'

app/views/admin/results/delete.html.haml
- title "Deleting result for #{@event.name}"

- content_for :sidebar do
  = render :partial => 'admin/sidebar'

- if notice.present?
  %p#notice.alert.alert-success= notice

%h1
  %i.icon-remove
  Deleting result for #{@event.name}

.row-fluid
  .section.span12
    %h4.title= icon_title_question 'Confirmation:'

    %div
      %p Are you sure you want to delete result for #{@event.name}</strong>?
      %p Doing so will trigger the following actions:
      %ul
        - case @result.type
        - when 'TeamResult'
          %li Remove this result from the #{link_to @result.participant.chapter, chapter_team_path(@result.participant.chapter, @result.participant)} team
        - else
          %li Remove this result from #{link_to @result.participant, chapter_student_path(@result.participant.chapter, @result.participant)}

    %div
      = link_to icon_title_delete,  admin_event_result_path(@event, @result), :method => :delete, :class => 'btn btn-small btn-danger'
      = link_to icon_title('arrow-left', 'Cancel'), :back, :class => 'btn btn-small'

app/views/admin/results/edit.html.haml
- title "Editing result for #{@event.name}"

- content_for :sidebar do
  = render :partial => 'admin/sidebar'

.row-fluid
  .span12
    %h1= icon_title_new "Editing result for #{link_to event_with_icon(@event), admin_event_path(@event)}"

.row-fluid
  .span12
    = render :partial => 'form'

app/views/admin/results/index.html.haml
- title "Results for #{@event.name}"

- content_for :sidebar do
  = render :partial => 'admin/sidebar'

- if notice.present?
  %p#notice.alert.alert-success= notice

- content_for :section_header do
  %h1= icon_title_result "Results for #{link_to event_with_icon(@event), admin_event_path(@event)}"

= render :partial => 'index', :locals => { :event => @event, :results => @results, :section_header => content_for(:section_header) }

app/views/admin/results/main.html.haml
- title 'Results'

- content_for :sidebar do
  = render :partial => 'admin/sidebar'

- if notice.present?
  %p#notice.alert.alert-success= notice

.row-fluid
  .section.span12
    %h1= icon_title_result "Results"

    .row-fluid
      .section.span12
        %h4.title= icon_title_event 'Events:'
        %div
          %table.table
            %tr
              %th Number
              %th Name
              %th Type
              %th Results
              %th

            - @events.each do |ev|
              = render :partial => 'admin/events/results_table_row', :locals => { :event => ev }

app/views/admin/results/new.html.haml
- title "New result for #{@event.name}"

- content_for :sidebar do
  = render :partial => 'admin/sidebar'

.row-fluid
  .span12
    %h1= icon_title_new "Adding a new result for #{link_to event_with_icon(@event), admin_event_path(@event)}"

.row-fluid
  .span12
    = render :partial => 'form'