config/routes.rb
BusinessSkillsDay::Application.routes.draw do

  # Define the root route, which will go the index action of the Main controller.
  root :to => 'main#index'

  # Session controller.
  get '/login' => 'sessions#new', :as => :new_login
  post '/login' => 'sessions#create', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout, :via => :all

  # Registration resource to allow a user to apply for a new chapter.
  resources :registrations, :only => [:index, :new, :create]

  # Account resource to access the current user's account.
  resource :account, :only => [:show, :edit, :update]

  # Chapter (and nested) resource.
  resources :chapters, :only => [:show, :edit, :update] do
    resources :advisers do get :delete, :on => :member end
    resources :students do get :delete, :on => :member end
    resources :teams do get :delete, :on => :member end
    get :results, :on => :member
  end

  # Admin namespace.
  namespace :admin do
    resources :chapters,  :except => [:show, :edit, :update] do get :delete, :on => :member end
    resources :advisers,  :except => [:new, :create, :show, :edit, :update]
    resources :students,  :except => [:new, :create, :show, :edit, :update]
    resources :teams,     :except => [:new, :create, :show, :edit, :update]

    resources :events do
      get :delete, :on => :member

      resources :results, :except => [:show] do
        get :delete, :on => :member
      end
    end

    resources :accounts do get :delete, :on => :member end

    resources :registrations, :only => [:index, :show, :edit, :update, :destroy] do
      get :delete, :on => :member
      get :confirm, :on => :member
      post :approve, :on => :member
    end

    # Tools like nametags, powerpoints, etc.
    scope :tools do
      get '/' => 'tools#index', :as => 'tools'
      get 'nametags' => 'tools#nametags'
    end

    get '/results' => 'results#main', :as => 'results'
    get '/' => 'main#index'
  end

end

app/views/admin/_sidebar.html.haml
%ul.nav.nav-list
  - case current_account
  - when AdminAccount
    = sidebar_header 'Admin', :icon => 'icon-key'
  - when StaffAccount
    = sidebar_header 'Staff', :icon => 'icon-shield'
  = sidebar_link 'Dashboard', admin_path, :controller => 'main', :action => ['index']
  = sidebar_link 'Chapters', admin_chapters_path, :controller => 'chapters', :action => ['index', 'new', 'create']
  = sidebar_link 'Advisers', admin_advisers_path, :controller => 'advisers', :action => ['index', 'new', 'create']
  = sidebar_link 'Students', admin_students_path, :controller => 'students', :action => ['index', 'new', 'create']
  = sidebar_link 'Teams', admin_teams_path, :controller => 'teams', :action => ['index', 'new', 'create']
  = sidebar_link 'Events', admin_events_path, :controller => 'events'
  = sidebar_link 'Results', admin_results_path, :controller => 'results'

  - if can? :manage, Account
    = sidebar_link 'Accounts', admin_accounts_path, :controller => 'accounts'

  - if can? :manage, Registration
    = sidebar_link 'Registrations', admin_registrations_path, :controller => 'registrations'

  = sidebar_link 'Tools', admin_tools_path, :controller => 'tools'